import { Factory, faker } from 'ember-cli-mirage';

export default Factory.extend({
  name() { return faker.lorem.word().toUpperCase(); },
  directionsForUse() { return faker.lorem.sentence(); },
  condition() {
    return faker.list.random(
      'Acute Coronary Syndrome',
      'Alcohol/Drug Abuse',
      'Allergies',
      'Alzheimer\'s Disease',
      'Anticoagulation',
      'Anxiety',
      'Arthritis',
      'Asthma',
      'Atrial Fibrillation',
      'Autoimmune Disorder',
      'Bipolar Disorder',
      'Bladder Control',
      'Blood Disorder',
      'Blood Disorder (Anemia)',
      'Brain Disorder (Neurologic)',
      'Cancer',
      'Cardiovascular Disease',
      'Chest Pain',
      'COPD',
      'Coronary Artery Disease',
      'Depression',
      'End Stage Liver Disease',
      'Enlarged Prostate',
      'Fluid Retention',
      'Gastrointestinal Disorder',
      'Glaucoma',
      'Gout',
      'Heart Failure',
      'Heartburn',
      'Hepatitis',
      'High Blood Pressure',
      'High Cholesterol',
      'HIV/AIDS',
      'Infectious Disease',
      'Kidney Disease',
      'Lung Disease',
      'Memory',
      'Mental Health Condition',
      'Mental Health Disorder (Schizophrenia)',
      'Mood Disorder',
      'Multiple Sclerosis',
      'Nerve Pain',
      'Osteoporosis',
      'Pain',
      'Parkinson\'s Disease',
      'Peripheral Artery Disease',
      'Restless Leg Syndrome',
      'Rheumatoid Arthritis',
      'Seizure Disorder',
      'Sexual Dysfunction',
      'Sleep Disorder',
      'Specialty Medication Management',
      'Stroke',
      'Supplement',
      'Thyroid Disorder',
      'Tobacco Use',
      'Weight Management'
    )();
  }
});
